### ISSUE TITLE
:transcoder argument not honored

### ISSUE THREAD

**Issue by CVTJNII** [nukemberg/riemann-redis-output#6]
In practice I'm seeing that the :transcoder argument isn't honored.  I have tried passing multiple values to :transcoder (including a string, in an attempt to elicit a exception) but none had any effect.  Looking at the code I don't believe this option is actually used.  It is used to generate a transcoder variable [on line 81](https://github.com/avishai-ish-shalom/riemann-flapjack-output/blob/master/src/riemann_flapjack_output/core.clj#L81) however that variable does not appear to be used.  The internal transcode-event function is used directly [on line 68](https://github.com/avishai-ish-shalom/riemann-flapjack-output/blob/master/src/riemann_flapjack_output/core.clj#L68).

Am I correct that the transcoder variable set on L81 isn't used, and transcode-event is used directly on L68?  If so, can we update it to use transcoder or remove that argument?

**Comment by avishai-ish-shalom** [comment]
you are correct. fixing.

**Comment by CVTJNII** [comment]
Thank you!
